"""add releations

Revision ID: 591ddfe3d440
Revises: 0a8aec9cc147
Create Date: 2023-08-11 08:57:19.625442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591ddfe3d440'
down_revision = '0a8aec9cc147'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_owner', 'owner', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy', schema=None) as batch_op:
        batch_op.drop_constraint('fk_owner', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
